when:
  event:
    - push
    - tag
    - deployment

steps:
  install:
    image: node
    commands:
      - npm install
  build:
    image: node
    depends_on:
      - install
    commands:
      - npm run build
  lint:
    image: node
    depends_on:
       - build
    commands:
      - npm run lint
  test:
    image: node
    depends_on:
       - build
    commands:
      - npm run test
