when:
  event:
    - tag
    - deployment

depends_on:
  - check

steps:
  install:
    image: node
    commands:
      - npm install
  prepare release:
    image: node
    depends_on:
      - install
    commands:
      - npm install @stdlib/utils-escape-regexp-string --no-save
      - node -e "console.log(require('@stdlib/utils-escape-regexp-string')('${CI_COMMIT_REF##refs/tags/}'))" > .tagName.txt
      - export TagName=$$(cat .tagName.txt)
      - echo "/^## \(.* \($${TagName}\|\[$${TagName}\]\)\)\$/" > .tagHeading.txt
  check release prerequisites:
    image: node
    secrets:
      - npm_token
      - ovsx_token
      - vsce_token
      - github_package_token
      - github_publish_token
    depends_on:
      - prepare release
    commands:
      - npm i --no-save @octokit/rest
      - >
        testNPM() {
          echo "//registry.npmjs.org/:_authToken=$1" > ~/.npmrc
          npm whoami > /dev/null 2>&1
        }
      - >
        testGitHub() {
          node -e 'new (require("@octokit/rest").Octokit)({ auth: "'"$1"'" }).request("GET /user").catch(() => process.exit(1))' > /dev/null 2>&1
        }
      - export PUBLISHER=$$(node -e "console.log(JSON.parse(require('fs').readFileSync('./packages/vscode/package.json').toString()).publisher)")
      - >
        testOVSX() {
          url='https://open-vsx.org/api/-/namespace/create?token='"$1"
          output=$(curl -X POST $url --header 'Content-Type: application/json' --data-raw '{ "name": "'"$PUBLISHER"'" }')
          node -e 'JSON.parse('"'$output'"').error?.includes("Invalid access token") && process.exit(1);'
        }
      - >
        testVSCE() {
          npx vsce verify-pat $PUBLISHER --pat $1 > /dev/null 2>&1
        }
      - export TagHeading=$$(cat .tagHeading.txt)
      - '[ ! -z "$$(sed "$${TagHeading}p;d" CHANGELOG.md)" ] || { echo "No Changelog Entries Found!" && false; }'
      - testNPM $NPM_TOKEN               || { echo "The NPM Access Token is invalid!" && false; }
      - testOVSX $OVSX_TOKEN             || { echo "The Open VSX Token is invalid!" && false; }
      - testVSCE $VSCE_TOKEN             || { echo "The Visual Studio Marketplace Token is invalid!" && false; }
      - testGitHub $GITHUB_PACKAGE_TOKEN || { echo "The GitHub Package Token is invalid!" && false; }
      - testGitHub $GITHUB_PUBLISH_TOKEN || { echo "The GitHub Publish Token is invalid!" && false; }
  create package:
    image: node
    depends_on:
      - check release prerequisites
    commands:
      - npm pack -w @typescript-nameof/nameof -w @typescript-nameof/types -w @typescript-nameof/babel -w @typescript-nameof/common -w @typescript-nameof/common-types
  create extension:
    image: node
    depends_on:
      - create package
    commands:
      - npm exec --workspace ./packages/vscode -- vsce package
      - npm run --prefix ./packages/vscode vscode:postpublish
  prepare release notes:
    image: alpine
    depends_on:
      - create package
    commands:
      - export TagName=$$(cat .tagName.txt)
      - export TagHeading=$$(cat .tagHeading.txt)
      - export HeadingPattern='/## \(.* \(v[0-9.]*\|\[.*\]\)\)/'
      - cp -f CHANGELOG.md .releaseNotes.md
      - sed -i "1,$${TagHeading}{ $${TagHeading}P ; d } ; $${HeadingPattern},\$d" .releaseNotes.md
      - cp -f .releaseNotes.md .releaseTitle.md
      - sed -i "2,\$d ; s$${HeadingPattern}\\\\1/" .releaseTitle.md
  publish package to npm:
    image: node
    secrets:
      - npm_token
    depends_on:
      - create package
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" > ~/.npmrc
      - npm publish --workspaces
    when:
      event: deployment
  publish package to github:
    image: node
    secrets:
      - github_package_token
    depends_on:
      - publish package to npm
    commands:
      - echo "//npm.pkg.github.com/:_authToken=$${GITHUB_PACKAGE_TOKEN}" > ~/.npmrc
      - echo "registry=https://npm.pkg.github.com" >> ~/.npmrc
      - npm publish --workspaces
    when:
      event: deployment
  publish extension to ovsx marketplace:
    image: node
    secrets:
      - ovsx_token
    depends_on:
      - create extension
    commands:
      - npm exec --workspace ./packages/vscode -- ovsx publish --pat $OVSX_TOKEN
      - npm run --prefix ./packages/vscode vscode:postpublish
    when:
      event: deployment
  publish extension to vscode marketplace:
    image: node
    secrets:
      - vsce_token
    depends_on:
      - publish extension to ovsx marketplace
    commands:
      - npm exec --workspace ./packages/vscode -- vsce publish --pat $VSCE_TOKEN
      - npm run --prefix ./packages/vscode vscode:postpublish
    when:
      event: deployment
  publish release:
    image: plugins/github-release
    depends_on:
      - publish extension to vscode marketplace
      - prepare release notes
    settings:
      api_key:
        from_secret: github_publish_token
      files:
        - "*.tgz"
        - "packages/vscode/*.vsix"
      title: .releaseTitle.md
      note: .releaseNotes.md
    when:
      event: tag
